import React, { useState } from "react";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import { Cart, Plus } from "react-bootstrap-icons";
import { data } from "react-router";
export var products = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 1199,
    ram: "8GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "48MP Main, 12MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41lQuD3zXhL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1299,
    ram: "12GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.8 inches",
    camera:
      "200MP Main, 12MP Ultra-Wide, 10MP Telephoto (x2), 10MP Telephoto (x5)",
    image_url: "https://m.media-amazon.com/images/I/41Vc86yXS3L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 3,
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 999,
    ram: "12GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "50MP Main, 48MP Ultra-Wide, 48MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/71r0349s3cL._SX679_.jpg",
  },
  {
    id: 4,
    name: "OnePlus 12",
    brand: "OnePlus",
    price: 899,
    ram: "16GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.82 inches",
    camera: "50MP Main, 48MP Ultra-Wide, 64MP Periscope Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41J4+TiUz6L._SY300_SX300_.jpg",
  },
  {
    id: 5,
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    price: 999,
    ram: "16GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.73 inches",
    camera: "50MP Quad Camera with Leica Optics",
    image_url: "https://m.media-amazon.com/images/I/41EQfoH+qFL._SY300_SX300_.jpg",
  },
  {
    id: 6,
    name: "iPhone SE (3rd Gen)",
    brand: "Apple",
    price: 429,
    ram: "4GB",
    rom: "64GB",
    category: "mobiles",
    screen_size: "4.7 inches",
    camera: "12MP Wide",
    image_url: "https://m.media-amazon.com/images/I/41BKXZLpc1L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 7,
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    price: 479,
    ram: "8GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.6 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 5MP Macro",
    image_url: "https://m.media-amazon.com/images/I/41uR6Pme6NL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 8,
    name: "Google Pixel 7a",
    brand: "Google",
    price: 499,
    ram: "8GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.1 inches",
    camera: "64MP Main, 13MP Ultra-Wide",
    image_url: "https://m.media-amazon.com/images/I/41YW3WpZ2ML._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 9,
    name: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    price: 399,
    ram: "12GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.67 inches",
    camera: "200MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://m.media-amazon.com/images/I/3170zY4OGWL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 10,
    name: "Realme 12 Pro+",
    brand: "Realme",
    price: 379,
    ram: "8GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 64MP Periscope Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41EcfoaB4+L._SY300_SX300_.jpg",
  },
  {
    id: 11,
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    price: 699,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 10MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41qtPl1QeHL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 12,
    name: "Nothing Phone (2)",
    brand: "Nothing",
    price: 699,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "50MP Main, 50MP Ultra-Wide",
    image_url:
      "https://m.media-amazon.com/images/I/51EGheCtg0L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 13,
    name: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    price: 1399,
    ram: "24GB",
    rom: "1TB",
    category: "mobiles",
    screen_size: "6.78 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 32MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41Safi-Gx1L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 14,
    name: "Sony Xperia 1 V",
    brand: "Sony",
    price: 1299,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.5 inches",
    camera: "48MP Main, 12MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41xJv6S3G6L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 15,
    name: "Vivo X100 Pro",
    brand: "Vivo",
    price: 899,
    ram: "16GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.78 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 50MP Periscope Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41C5enOglKL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 16,
    name: "Oppo Find X7 Ultra",
    brand: "Oppo",
    price: 1099,
    ram: "16GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.82 inches",
    camera: "50MP Quad Camera with HyperTone",
    image_url: "https://m.media-amazon.com/images/I/41toJG9uWkL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 17,
    name: "Honor Magic6 Pro",
    brand: "Honor",
    price: 1099,
    ram: "12GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.8 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 180MP Periscope Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41YapxuVy9L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 18,
    name: "Huawei P60 Pro",
    brand: "Huawei",
    price: 999,
    ram: "8GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.67 inches",
    camera: "48MP Main, 13MP Ultra-Wide, 48MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/71nYEHgLodL._SX569_.jpg",
  },
  {
    id: 19,
    name: "Infinix Note 40 Pro+",
    brand: "Infinix",
    price: 299,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.78 inches",
    camera: "108MP Main, 2MP Macro, 2MP Depth",
    image_url: "https://m.media-amazon.com/images/I/51-Unh3XuBL.jpg",
  },
  {
    id: 20,
    name: "Tecno Camon 30 Pro 5G",
    brand: "Tecno",
    price: 349,
    ram: "12GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "6.78 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 2MP Depth",
    image_url: "https://m.media-amazon.com/images/I/41cHIrr45WL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 21,
    name: "iPhone 14 Pro",
    brand: "Apple",
    price: 999,
    ram: "6GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.1 inches",
    camera: "48MP Main, 12MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/31VjlrbE3bL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 22,
    name: "Samsung Galaxy Z Fold5",
    brand: "Samsung",
    price: 1799,
    ram: "12GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "7.6 inches (unfolded)",
    camera: "50MP Main, 12MP Ultra-Wide, 10MP Telephoto",
    image_url: "",
  },
  {
    id: 23,
    name: "Google Pixel Fold",
    brand: "Google",
    price: 1699,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "7.6 inches (unfolded)",
    camera: "48MP Main, 10.8MP Ultra-Wide, 10.8MP Telephoto",
    image_url: "",
  },
  {
    id: 24,
    name: "OnePlus Open",
    brand: "OnePlus",
    price: 1599,
    ram: "16GB",
    rom: "512GB",
    category: "mobiles",
    screen_size: "7.82 inches (unfolded)",
    camera: "48MP Main, 48MP Ultra-Wide, 64MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/51VuJpFmjrL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 25,
    name: "Motorola Razr+",
    brand: "Motorola",
    price: 999,
    ram: "8GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.9 inches (unfolded)",
    camera: "12MP Main, 13MP Ultra-Wide",
    image_url: "https://m.media-amazon.com/images/I/31dRswun9WL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 26,
    name: "Samsung Galaxy Z Flip5",
    brand: "Samsung",
    price: 999,
    ram: "8GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches (unfolded)",
    camera: "12MP Main, 12MP Ultra-Wide",
    image_url: "https://m.media-amazon.com/images/I/3114411coLL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 27,
    name: "iPhone 15",
    brand: "Apple",
    price: 799,
    ram: "6GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.1 inches",
    camera: "48MP Main, 12MP Ultra-Wide",
    image_url: "https://m.media-amazon.com/images/I/31KxpX7Xk7L._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 28,
    name: "Samsung Galaxy S24+",
    brand: "Samsung",
    price: 999,
    ram: "12GB",
    rom: "256GB",
    category: "mobiles",
    screen_size: "6.7 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 10MP Telephoto",
    image_url: "https://m.media-amazon.com/images/I/41h2alWH8ML._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 29,
    name: "Google Pixel 8",
    brand: "Google",
    price: 699,
    ram: "8GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.2 inches",
    camera: "50MP Main, 12MP Ultra-Wide",
    image_url: "https://m.media-amazon.com/images/I/417PLOtA3HL._SY300_SX300_.jpg",
  },
  {
    id: 30,
    name: "OnePlus 12R",
    brand: "OnePlus",
    price: 499,
    ram: "8GB",
    rom: "128GB",
    category: "mobiles",
    screen_size: "6.78 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://m.media-amazon.com/images/I/41uPss3u3eL._SX300_SY300_QL70_FMwebp_.jpg",
  },
  {
    id: 31,
    name: "Xiaomi 14",
    brand: "Xiaomi",
    price: 799,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.36 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 50MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?xiaomi,black",
  },
  {
    id: 32,
    name: "Realme GT 5 Pro",
    brand: "Realme",
    price: 599,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 50MP Periscope Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?realme,gt",
  },
  {
    id: 33,
    name: "Motorola Edge 40 Neo",
    brand: "Motorola",
    price: 399,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.55 inches",
    camera: "50MP Main, 13MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?motorola,neo",
  },
  {
    id: 34,
    name: "Nothing Phone (2a)",
    brand: "Nothing",
    price: 349,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "50MP Main, 50MP Ultra-Wide",
    image_url:
      "https://source.unsplash.com/random/800x600?nothingphone,affordable",
  },
  {
    id: 35,
    name: "ASUS Zenfone 11 Ultra",
    brand: "ASUS",
    price: 999,
    ram: "16GB",
    rom: "512GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 32MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?asus,zenfone",
  },
  {
    id: 36,
    name: "Sony Xperia 5 V",
    brand: "Sony",
    price: 899,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.1 inches",
    camera: "48MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?sony,compact",
  },
  {
    id: 37,
    name: "Vivo iQOO 12",
    brand: "Vivo",
    price: 799,
    ram: "16GB",
    rom: "512GB",
    category: "Gaming Phone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 64MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?iqoo,gaming",
  },
  {
    id: 38,
    name: "Oppo Reno11 Pro 5G",
    brand: "Oppo",
    price: 549,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 32MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?oppo,reno",
  },
  {
    id: 39,
    name: "Honor 90",
    brand: "Honor",
    price: 499,
    ram: "12GB",
    rom: "512GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "200MP Main, 12MP Ultra-Wide, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?honor,90",
  },
  {
    id: 40,
    name: "Huawei Mate 60 Pro+",
    brand: "Huawei",
    price: 1199,
    ram: "16GB",
    rom: "1TB",
    category: "Smartphone",
    screen_size: "6.82 inches",
    camera: "48MP Main, 40MP Ultra-Wide, 48MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?huawei,mate",
  },
  {
    id: 41,
    name: "iPhone 13 mini",
    brand: "Apple",
    price: 599,
    ram: "4GB",
    rom: "128GB",
    category: "Compact Smartphone",
    screen_size: "5.4 inches",
    camera: "12MP Wide, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?iphone,mini",
  },
  {
    id: 42,
    name: "Samsung Galaxy A35",
    brand: "Samsung",
    price: 379,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.6 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 5MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?samsung,midrange",
  },
  {
    id: 43,
    name: "Google Pixel 7",
    brand: "Google",
    price: 599,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.3 inches",
    camera: "50MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?pixel,orange",
  },
  {
    id: 44,
    name: "Redmi Note 13 5G",
    brand: "Xiaomi",
    price: 249,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "108MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?redmi,blue",
  },
  {
    id: 45,
    name: "Realme 12+ 5G",
    brand: "Realme",
    price: 299,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?realme,white",
  },
  {
    id: 46,
    name: "Motorola G Power 5G (2024)",
    brand: "Motorola",
    price: 299,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "50MP Main, 8MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?motorola,gpower",
  },
  {
    id: 47,
    name: "POCO X6 Pro 5G",
    brand: "POCO",
    price: 359,
    ram: "12GB",
    rom: "512GB",
    category: "Gaming Phone",
    screen_size: "6.67 inches",
    camera: "64MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?poco,gaming",
  },
  {
    id: 48,
    name: "ASUS ROG Phone 7",
    brand: "ASUS",
    price: 999,
    ram: "16GB",
    rom: "512GB",
    category: "Gaming Phone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 5MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?rogphone,black",
  },
  {
    id: 49,
    name: "Sony Xperia 10 V",
    brand: "Sony",
    price: 449,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.1 inches",
    camera: "48MP Main, 8MP Ultra-Wide, 8MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?sony,affordable",
  },
  {
    id: 50,
    name: "Vivo V30 Pro",
    brand: "Vivo",
    price: 499,
    ram: "12GB",
    rom: "512GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 50MP Ultra-Wide, 50MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?vivo,v30",
  },
  {
    id: 51,
    name: "Oppo Find N3 Flip",
    brand: "Oppo",
    price: 999,
    ram: "12GB",
    rom: "256GB",
    category: "Foldable Phone",
    screen_size: "6.8 inches (unfolded)",
    camera: "50MP Main, 48MP Ultra-Wide, 32MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?oppo,flip",
  },
  {
    id: 52,
    name: "Honor Magic V2",
    brand: "Honor",
    price: 1699,
    ram: "16GB",
    rom: "512GB",
    category: "Foldable Phone",
    screen_size: "7.92 inches (unfolded)",
    camera: "50MP Main, 50MP Ultra-Wide, 20MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?honor,fold",
  },
  {
    id: 53,
    name: "Huawei Mate X3",
    brand: "Huawei",
    price: 1899,
    ram: "12GB",
    rom: "512GB",
    category: "Foldable Phone",
    screen_size: "7.85 inches (unfolded)",
    camera: "50MP Main, 13MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?huawei,foldable",
  },
  {
    id: 54,
    name: "Infinix Zero 30 5G",
    brand: "Infinix",
    price: 279,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "108MP Main, 13MP Ultra-Wide, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?infinix,zero",
  },
  {
    id: 55,
    name: "Tecno Spark 20 Pro+",
    brand: "Tecno",
    price: 229,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "108MP Main, 2MP Macro, 0.08MP Aux",
    image_url: "https://source.unsplash.com/random/800x600?tecno,spark",
  },
  {
    id: 56,
    name: "iPhone 15 Plus",
    brand: "Apple",
    price: 899,
    ram: "6GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "48MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?iphone,blue",
  },
  {
    id: 57,
    name: "Samsung Galaxy S23 FE",
    brand: "Samsung",
    price: 599,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.4 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 8MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?samsung,fe",
  },
  {
    id: 58,
    name: "Google Pixel 6a",
    brand: "Google",
    price: 349,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.1 inches",
    camera: "12.2MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?pixel,grey",
  },
  {
    id: 59,
    name: "Redmi 13C",
    brand: "Xiaomi",
    price: 149,
    ram: "4GB",
    rom: "128GB",
    category: "Budget Smartphone",
    screen_size: "6.74 inches",
    camera: "50MP Main, 2MP Macro, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?redmi,cheap",
  },
  {
    id: 60,
    name: "Realme C67 5G",
    brand: "Realme",
    price: 199,
    ram: "6GB",
    rom: "128GB",
    category: "Budget Smartphone",
    screen_size: "6.72 inches",
    camera: "50MP Main, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?realme,cseries",
  },
  {
    id: 61,
    name: "Motorola Moto G54 5G",
    brand: "Motorola",
    price: 249,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.5 inches",
    camera: "50MP Main, 8MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?motorola,gseries",
  },
  {
    id: 62,
    name: "Nothing Phone (1)",
    brand: "Nothing",
    price: 399,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.55 inches",
    camera: "50MP Main, 50MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?nothingphone,white",
  },
  {
    id: 63,
    name: "ASUS Zenfone 10",
    brand: "ASUS",
    price: 699,
    ram: "8GB",
    rom: "128GB",
    category: "Compact Smartphone",
    screen_size: "5.9 inches",
    camera: "50MP Main, 13MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?asus,compact",
  },
  {
    id: 64,
    name: "Sony Xperia 1 IV",
    brand: "Sony",
    price: 999,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.5 inches",
    camera: "12MP Quad Camera",
    image_url: "https://source.unsplash.com/random/800x600?sony,flagship",
  },
  {
    id: 65,
    name: "Vivo X90 Pro",
    brand: "Vivo",
    price: 799,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 50MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?vivo,xseries",
  },
  {
    id: 66,
    name: "Oppo Reno10 Pro+ 5G",
    brand: "Oppo",
    price: 699,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 64MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?oppo,proplus",
  },
  {
    id: 67,
    name: "Honor Magic5 Pro",
    brand: "Honor",
    price: 899,
    ram: "12GB",
    rom: "512GB",
    category: "Smartphone",
    screen_size: "6.81 inches",
    camera: "50MP Triple Camera",
    image_url: "https://source.unsplash.com/random/800x600?honor,magicpro",
  },
  {
    id: 68,
    name: "Huawei P50 Pro",
    brand: "Huawei",
    price: 799,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.6 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 64MP Telephoto, 40MP Mono",
    image_url: "https://source.unsplash.com/random/800x600?huawei,p50",
  },
  {
    id: 69,
    name: "Infinix Hot 40 Pro",
    brand: "Infinix",
    price: 179,
    ram: "8GB",
    rom: "256GB",
    category: "Budget Smartphone",
    screen_size: "6.78 inches",
    camera: "108MP Main, 2MP Macro, AI Cam",
    image_url: "https://source.unsplash.com/random/800x600?infinix,hot",
  },
  {
    id: 70,
    name: "Tecno Pova 6 Pro 5G",
    brand: "Tecno",
    price: 279,
    ram: "12GB",
    rom: "256GB",
    category: "Gaming Phone",
    screen_size: "6.78 inches",
    camera: "108MP Main, 2MP Macro, 0.08MP Aux",
    image_url: "https://source.unsplash.com/random/800x600?tecno,pova",
  },
  {
    id: 71,
    name: "iPhone 14",
    brand: "Apple",
    price: 699,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.1 inches",
    camera: "12MP Wide, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?iphone,black",
  },
  {
    id: 72,
    name: "Samsung Galaxy A15 5G",
    brand: "Samsung",
    price: 199,
    ram: "4GB",
    rom: "128GB",
    category: "Budget Smartphone",
    screen_size: "6.5 inches",
    camera: "50MP Main, 5MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?samsung,entrylevel",
  },
  {
    id: 73,
    name: "Google Pixel 6 Pro",
    brand: "Google",
    price: 799,
    ram: "12GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 48MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?pixel,pro",
  },
  {
    id: 74,
    name: "Redmi K70 Pro",
    brand: "Xiaomi",
    price: 499,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "50MP Main, 12MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?redmi,kseries",
  },
  {
    id: 75,
    name: "Realme GT Neo 6 SE",
    brand: "Realme",
    price: 349,
    ram: "12GB",
    rom: "256GB",
    category: "Gaming Phone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 8MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?realme,neo",
  },
  {
    id: 76,
    name: "Motorola Edge 30 Ultra",
    brand: "Motorola",
    price: 799,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "200MP Main, 50MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?motorola,ultra",
  },
  {
    id: 77,
    name: "POCO F5 Pro",
    brand: "POCO",
    price: 449,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "64MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?poco,fseries",
  },
  {
    id: 78,
    name: "ASUS ROG Phone 6D Ultimate",
    brand: "ASUS",
    price: 1099,
    ram: "16GB",
    rom: "512GB",
    category: "Gaming Phone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 13MP Ultra-Wide, 5MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?rogphone,ultimate",
  },
  {
    id: 79,
    name: "Sony Xperia Pro-I",
    brand: "Sony",
    price: 1799,
    ram: "12GB",
    rom: "512GB",
    category: "Pro Camera Phone",
    screen_size: "6.5 inches",
    camera: "1-inch 12MP Main, 12MP Ultra-Wide, 12MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?sony,proi",
  },
  {
    id: 80,
    name: "Vivo X Flip",
    brand: "Vivo",
    price: 899,
    ram: "12GB",
    rom: "256GB",
    category: "Foldable Phone",
    screen_size: "6.74 inches (unfolded)",
    camera: "50MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?vivo,flip",
  },
  {
    id: 81,
    name: "Oppo Find N2 Flip",
    brand: "Oppo",
    price: 899,
    ram: "8GB",
    rom: "256GB",
    category: "Foldable Phone",
    screen_size: "6.8 inches (unfolded)",
    camera: "50MP Main, 8MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?oppo,flip",
  },
  {
    id: 82,
    name: "Honor Magic Vs",
    brand: "Honor",
    price: 1499,
    ram: "12GB",
    rom: "512GB",
    category: "Foldable Phone",
    screen_size: "7.9 inches (unfolded)",
    camera: "54MP Main, 50MP Ultra-Wide, 8MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?honor,vs",
  },
  {
    id: 83,
    name: "Huawei Mate Xs 2",
    brand: "Huawei",
    price: 1999,
    ram: "8GB",
    rom: "512GB",
    category: "Foldable Phone",
    screen_size: "7.8 inches (unfolded)",
    camera: "50MP Main, 13MP Ultra-Wide, 8MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?huawei,fold",
  },
  {
    id: 84,
    name: "Infinix Zero Ultra",
    brand: "Infinix",
    price: 499,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.8 inches",
    camera: "200MP Main, 13MP Ultra-Wide, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?infinix,ultra",
  },
  {
    id: 85,
    name: "Tecno Phantom X2 Pro",
    brand: "Tecno",
    price: 699,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.8 inches",
    camera: "50MP Main (retractable), 50MP Telephoto, 13MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?tecno,phantom",
  },
  {
    id: 86,
    name: "iPhone 13",
    brand: "Apple",
    price: 699,
    ram: "4GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.1 inches",
    camera: "12MP Wide, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?iphone,green",
  },
  {
    id: 87,
    name: "Samsung Galaxy A25 5G",
    brand: "Samsung",
    price: 279,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.5 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?samsung,a25",
  },
  {
    id: 88,
    name: "Google Pixel 5a 5G",
    brand: "Google",
    price: 299,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.34 inches",
    camera: "12.2MP Main, 16MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?pixel,budget",
  },
  {
    id: 89,
    name: "Redmi Note 12 Pro",
    brand: "Xiaomi",
    price: 299,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "50MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?redmi,note",
  },
  {
    id: 90,
    name: "Realme 11 Pro+",
    brand: "Realme",
    price: 379,
    ram: "12GB",
    rom: "512GB",
    category: "Smartphone",
    screen_size: "6.7 inches",
    camera: "200MP Main, 8MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?realme,pro",
  },
  {
    id: 91,
    name: "Motorola Edge 40",
    brand: "Motorola",
    price: 499,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.55 inches",
    camera: "50MP Main, 13MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?motorola,edge",
  },
  {
    id: 92,
    name: "POCO M6 Pro 5G",
    brand: "POCO",
    price: 179,
    ram: "6GB",
    rom: "128GB",
    category: "Budget Smartphone",
    screen_size: "6.79 inches",
    camera: "50MP Main, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?poco,mseries",
  },
  {
    id: 93,
    name: "ASUS Zenfone 9",
    brand: "ASUS",
    price: 599,
    ram: "8GB",
    rom: "128GB",
    category: "Compact Smartphone",
    screen_size: "5.9 inches",
    camera: "50MP Main, 12MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?asus,compact",
  },
  {
    id: 94,
    name: "Sony Xperia 10 IV",
    brand: "Sony",
    price: 349,
    ram: "6GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.0 inches",
    camera: "12MP Main, 8MP Ultra-Wide, 8MP Telephoto",
    image_url: "https://source.unsplash.com/random/800x600?sony,budget",
  },
  {
    id: 95,
    name: "Vivo Y200e 5G",
    brand: "Vivo",
    price: 249,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.67 inches",
    camera: "50MP Main, 2MP Depth",
    image_url: "https://source.unsplash.com/random/800x600?vivo,yseries",
  },
  {
    id: 96,
    name: "Oppo A79 5G",
    brand: "Oppo",
    price: 279,
    ram: "8GB",
    rom: "128GB",
    category: "Smartphone",
    screen_size: "6.72 inches",
    camera: "50MP Main, 2MP Portrait",
    image_url: "https://source.unsplash.com/random/800x600?oppo,aseries",
  },
  {
    id: 97,
    name: "Honor X9b",
    brand: "Honor",
    price: 399,
    ram: "12GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "108MP Main, 5MP Ultra-Wide, 2MP Macro",
    image_url: "https://source.unsplash.com/random/800x600?honor,xseries",
  },
  {
    id: 98,
    name: "Huawei Nova 11 Pro",
    brand: "Huawei",
    price: 599,
    ram: "8GB",
    rom: "256GB",
    category: "Smartphone",
    screen_size: "6.78 inches",
    camera: "50MP Main, 8MP Ultra-Wide",
    image_url: "https://source.unsplash.com/random/800x600?huawei,nova",
  },
  {
    id: 99,
    name: "Infinix Smart 8 Pro",
    brand: "Infinix",
    price: 129,
    ram: "4GB",
    rom: "64GB",
    category: "Entry-level Smartphone",
    screen_size: "6.6 inches",
    camera: "50MP Main, AI Cam",
    image_url: "https://source.unsplash.com/random/800x600?infinix,smart",
  },
  {
    id: 100,
    name: "Tecno Spark 10 Pro",
    brand: "Tecno",
    price: 169,
    ram: "8GB",
    rom: "128GB",
    category: "Budget Smartphone",
    screen_size: "6.8 inches",
    camera: "50MP Main, AI Cam",
    image_url: "https://source.unsplash.com/random/800x600?tecno,spark",
  },
];

export var selectedItems=[]
export const Product = () => {

  const [productValue,setProductValue] = useState(products)

  const[value,setValue] = useState('xyz')
  function filterData(){
    const filterdata = products.filter((data)=>data.id ===value)
    console.log(filterdata)
    setProductValue(filterdata)
  }
  function addItems(item){
    selectedItems.push(item)
    localStorage.setItem("cartItems",JSON.stringify(selectedItems))//this store data in ls.
    console.log(selectedItems)
  }
  return (
    <div className="shopping">
      <Container fluid>
        <Row className="row">
          {/* <Col>
            
            <div>
              {products.map((node) => (
                 <label>{node.brand}
                 <input className="w-100" type="checkbox" onChange={(e)=>{setValue(node.id)}} onClick={filterData} value ={value} key={products.name}/></label>

              ))}
              
            </div>
          </Col> */}

          {productValue.map((data) => (
            <Col sm={12} md={3}>
              <Card className="shop" style={{ width: "100%" }}>
                <Card.Img variant="top" src={data.image_url} className="item" />
                <Card.Body>
                  <Card.Title>{data.name}</Card.Title>
                  <Card.Text>{data.brand}</Card.Text>
                  <Card.Text>
                    Price:
                    {data.price >= parseFloat(100.0)
                      ? (data.price * 20) / 100
                      : data.price}
                  </Card.Text>
                  <Button variant="primary" onClick={()=>{
                      addItems(data.id)
                    }}>
                    <Plus /> Add Item{" "}
                  </Button>
                  <Button variant="primary">
                    <Cart /> Buy Now
                  </Button>
                </Card.Body>
              </Card>
            </Col>
          ))}
        </Row>
        <Row className="nh">
          <Col className="w-100">
            <h6>Back to top</h6>
          </Col>
        </Row>
      </Container>
    </div>
  );
};
